Release check
Ensembl/ensembl-prodinf-legacy-core pull request #116
Opened 2020-06-02 08:23 UTC by thomasmaurel

Added new check to make sure handed over database release version match the handover service release. This is getting schema version from the meta table instead of parsing the database name. Added code to drop a database from staging if the metadata load fails after copy. 
I started the PR on stable, then merged to master so the extra files are coming from commits on stable so no worries about this

2020-06-02 08:40 UTC, marcoooo requested changes

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +    def print_inputs(self, i):
Don't know it this function can't be just the logging.info("Received Parameters: %s", i). 
Python will manage the key / value dumps. whatever is in the initial dictionary. since key as "self meaning", we won't have to update this method each time we update the dictionary content.

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/rest_client.py
> +            logging.info("failed to submit because: "+r.text)
```suggestion
            logging.error("failed to submit because: "+r.text)
```

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/rest_client.py
> +            logging.info("failed to delete job because: "+r.text)
```suggestion
            logging.error("failed to delete job because: "+r.text)
```

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/rest_client.py
> +            logging.info("failed to list jobs because: "+r.text)
```suggestion
            logging.error("failed to list jobs because: "+r.text)
```

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/rest_client.py
> +            logging.info("failed to retrieve job failures because: "+r.text)
```suggestion
            logging.error("failed to retrieve job failures because: "+r.text)
```

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/rest_client.py
> +            logging.info("failed to retrieve job because: "+r.text)
```suggestion
            logging.error("failed to retrieve job because: "+r.text)
```

2020-06-02 08:40 UTC, marcoooo commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +            logging.info("User name: " + i['user'])
```suggestion
            logging.info("Detailed parameters:")
            logging.info("%s", i)
```

2020-06-02 08:46 UTC, thomasmaurel commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +    def print_inputs(self, i):
Yes that's possible, I mean this file is already on stable and it's not really the aim of this PR...

2020-06-02 10:33 UTC, luca-drf approved these changes

2020-06-02 10:43 UTC, marcoooo requested changes

2020-06-02 10:43 UTC, marcoooo commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +            if user:
Can you tell me the difference in else ? At first glance it seems you are always logging the same infos, whatever is the test outcome.
`logging.info("Job %s from (%s) to (%s) by %s - status: %s" % (job['url'], job['src_host'], job['tgt_host'], job['user'], job['overall_status']))`

2020-06-02 10:46 UTC, thomasmaurel commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +            if user:
If you give the script a user, it will only log jobs for this user else it will print jobs for all users.

2020-06-02 16:17 UTC, thomasmaurel commented on ensembl_prodinf/ensembl_dbcopy_client.py
> +            if user:
@marcoooo The check on url is because I am reusing the same method for different endpoints . The url is only available when we do a list: http://production-services.ensembl.org/api/dbcopy/requestjob
If we do a list, I am using job_id instead: http://production-services.ensembl.org/api/dbcopy/requestjob/0a29370e-1c2a-11ea-84f5-9801a79243a5.
Again, this PR was not really about this script...

2020-06-03 16:20 UTC, marcoooo approved these changes

2020-06-03 16:21 UTC, merged