Bugfixes/dcoutput empty
Ensembl/ensembl-prodinf-legacy-core pull request #134
Opened 2020-11-10 16:57 UTC by marcoooo

Related to EP-6199 - see related in `prodinf-srv`

2020-11-10 17:52 UTC, radome requested changes

2020-11-10 17:52 UTC, radome commented on ensembl_prodinf/handover_tasks.py
> +retry_wait = app.conf.get('retry_wait', 60)
Already defined at line 41.

```suggestion
```

2020-11-10 17:54 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +retry_wait = app.conf.get('retry_wait', 60)
This is not something I added. But never too late to fix this as well.

2020-11-10 18:30 UTC, radome commented on ensembl_prodinf/handover_tasks.py
> +retry_wait = app.conf.get('retry_wait', 60)
It could've been that has slipped in an automatic merge who knows when...

2020-11-11 10:06 UTC, james-monkeyshines approved these changes

2020-11-11 11:54 UTC, radome approved these changes

2020-11-30 16:39 UTC, merged