Revert "Better support new assembly"
Ensembl/ensembl-prodinf-legacy-core pull request #30
Opened 2018-11-07 14:33 UTC by thomasmaurel

Reverts Ensembl/ensembl-prodinf-core#29.

I will create a new PR for making the code a bit more pythony.

2018-11-07 14:36 UTC, thomasmaurel commented
This code should be done in the metadata updater perl API and not in the handover task

2018-11-07 17:07 UTC, thomasmaurel commented
Is this ok @marcoooo ?

2018-11-08 09:42 UTC, marcoooo requested changes

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (compara_uri == None):
```suggestion
    if compara_uri is None:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if(database_exists(uri) == False):
```suggestion
    if not database_exists(uri):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if(species_pattern.match(database)):
```suggestion
    if species_pattern.match(database):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(compara_pattern.match(database)):
```suggestion
     elif compara_pattern.match(database):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(ancestral_pattern.match(database)):
```suggestion
    elif ancestral_pattern.match(database):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if(db_type in ['core','rnaseq','cdna','otherfeatures']):
```suggestion
    if db_type in ['core','rnaseq','cdna','otherfeatures']:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'variation'):
```suggestion
    elif db_type == 'variation':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'funcgen'):
```suggestion
    elif db_type == 'funcgen':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'ancestral'):
```suggestion
    elif db_type == 'ancestral':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'compara'):
```suggestion
    elif db_type == 'compara':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'compara'):
```suggestion
    elif db_type == 'compara':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +        if (db_prefix == "pan"):
```suggestion
        if db_prefix == "pan":
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +        elif (check_grch37(uri,'homo_sapiens')):
```suggestion
        elif check_grch37(uri,'homo_sapiens'):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +        elif (db_prefix):
```suggestion
        elif db_prefix:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if('bacteria' in db_prefix):
```suggestion
    if 'bacteria' in db_prefix:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_prefix == 'homo_sapiens' and assembly == '37'):
```suggestion
    elif db_prefix == 'homo_sapiens' and assembly == '37':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif(db_type == 'compara' and check_grch37(spec['src_uri'],'homo_sapiens')):
```suggestion
    elif db_type == 'compara' and check_grch37(spec['src_uri'],'homo_sapiens'):
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'incomplete') or (result['status'] == 'running') or (result['status'] == 'submitted'):
```suggestion
    if result['status'] in ['incomplete', 'running', 'submitted']:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'failed'):
```suggestion
    if result['status'] == 'failed':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif (result['output']['status'] == 'failed'):
```suggestion
    elif result['output']['status'] == 'failed':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'incomplete') or (result['status'] == 'running') or (result['status'] == 'submitted'):
```suggestion
    if result['status'] in ['incomplete', 'running', 'submitted']:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'failed'):
```suggestion
    if result['status'] == 'failed':
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    elif('GRCh37'in spec):
```suggestion
    elif 'GRCh37'in spec:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'incomplete') or (result['status'] == 'running') or (result['status'] == 'submitted'):
```suggestion
    if result['status'] in ['incomplete', 'running', 'submitted']:
```

2018-11-08 09:42 UTC, marcoooo commented on ensembl_prodinf/handover_tasks.py
> +    if (result['status'] == 'failed'):
```suggestion
    if result['status'] == 'failed':
```

2018-11-08 09:53 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +    elif (result['output']['status'] == 'failed'):
Making code more Pythony

2018-11-08 13:49 UTC, thomasmaurel commented
Ok to merge now @marcoooo ?

2018-11-08 16:32 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +    elif(compara_pattern.match(database)):
@marcoooo: You added space by mistake here. This will break the whole file.

2018-11-08 16:34 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +    elif(compara_pattern.match(database)):
```suggestion
   elif(compara_pattern.match(database)):
```

2018-11-08 16:35 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +    elif(compara_pattern.match(database)):
```suggestion
    elif compara_pattern.match(database):
```

2018-11-08 16:39 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +     elif compara_pattern.match(database):
```suggestion
    elif compara_pattern.match(database):
```

2018-11-08 16:39 UTC, thomasmaurel commented on ensembl_prodinf/handover_tasks.py
> +    elif(compara_pattern.match(database)):
Ok, I will create a fix for this @marcoooo

2018-11-08 16:42 UTC, thomasmaurel commented
@marcoooo: I think this can be merged now.

2018-11-08 17:06 UTC, marcoooo approved these changes

2018-11-08 17:07 UTC, merged