Release/3.1
Ensembl/ensembl-prodinf-legacy-core pull request #71
Opened 2020-01-23 17:05 UTC by radome

2020-01-23 17:16 UTC, marcoooo requested changes

2020-01-23 17:16 UTC, marcoooo commented on docs/conf.py
> +copyright = '2017 EMBL-EBI'
Could you update this to 2020 please ?

2020-01-23 17:16 UTC, marcoooo commented on ensembl/server_utils.py
> +http_uri_regex = r"^(http){1}(s){0,1}(://){1}(.+){1}(:){1}(\d+){1}(/){1}(.+){0,1}$"
Is it not the file you modified somehow to resolve this uri checks ?

2020-01-23 17:16 UTC, marcoooo commented on ensembl_prodinf/server_utils.py
> +    parsed_uri = urlparse(uri)
This is the one you updated, so the other one is a copy to update as well... waiting for the both files to be merged.

2020-01-24 15:54 UTC, radome commented on docs/conf.py
> +copyright = '2017 EMBL-EBI'
See #73

2020-01-24 15:55 UTC, radome commented on ensembl_prodinf/server_utils.py
> +    parsed_uri = urlparse(uri)
See #73

2020-01-27 16:29 UTC, marcoooo approved these changes

2020-01-28 09:31 UTC, merged